# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Aurora Guides
tagline:          Visual novel workshop
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://guides.aurora.project-yoru.com
baseurl:          /

# TODO
author:
  name:           Nano WANG
  url:            https://twitter.com/nano_mid_wang

paginate:         5

# Custom vars
version:          pre-alpha
links:
  project_yoru: http://www.project-yoru.com
  aurora_web: http://aurora.project-yoru.com
# github:
#   repo:           https://github.com/project-yoru/aurora-guides
#   url: https://project-yoru.github.io/aurora-guides/

gems:
  - jekyll-paginate
  - jekyll-gist

pages: ./_pages
